name: /home/sobhan/environments/flash
channels:
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - asttokens=3.0.0=py313h06a4308_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - comm=0.2.1=py313h06a4308_0
  - cuda-cccl_linux-64=12.6.77=0
  - cuda-command-line-tools=12.6.3=0
  - cuda-compiler=12.6.3=0
  - cuda-crt-dev_linux-64=12.6.85=0
  - cuda-crt-tools=12.6.85=0
  - cuda-cudart=12.6.77=0
  - cuda-cudart-dev=12.6.77=0
  - cuda-cudart-dev_linux-64=12.6.77=0
  - cuda-cudart-static=12.6.77=0
  - cuda-cudart-static_linux-64=12.6.77=0
  - cuda-cudart_linux-64=12.6.77=0
  - cuda-cuobjdump=12.6.77=0
  - cuda-cupti=12.6.80=0
  - cuda-cupti-dev=12.6.80=0
  - cuda-cuxxfilt=12.6.77=0
  - cuda-driver-dev=12.6.77=0
  - cuda-driver-dev_linux-64=12.6.77=0
  - cuda-gdb=12.6.77=0
  - cuda-libraries=12.6.3=0
  - cuda-libraries-dev=12.6.3=0
  - cuda-nsight=12.6.77=0
  - cuda-nvcc=12.6.85=0
  - cuda-nvcc-dev_linux-64=12.6.85=0
  - cuda-nvcc-impl=12.6.85=0
  - cuda-nvcc-tools=12.6.85=0
  - cuda-nvcc_linux-64=12.6.85=0
  - cuda-nvdisasm=12.6.77=0
  - cuda-nvml-dev=12.6.77=2
  - cuda-nvprof=12.6.80=0
  - cuda-nvprune=12.6.77=0
  - cuda-nvrtc=12.6.85=0
  - cuda-nvrtc-dev=12.6.85=0
  - cuda-nvtx=12.6.77=0
  - cuda-nvvm-dev_linux-64=12.6.85=0
  - cuda-nvvm-impl=12.6.85=0
  - cuda-nvvm-tools=12.6.85=0
  - cuda-nvvp=12.6.80=0
  - cuda-opencl=12.6.77=0
  - cuda-opencl-dev=12.6.77=0
  - cuda-profiler-api=12.6.77=0
  - cuda-sanitizer-api=12.6.77=0
  - cuda-toolkit=12.6.3=0
  - cuda-tools=12.6.3=0
  - cuda-version=12.6=3
  - cuda-visual-tools=12.6.3=0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.11=py313h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.13.3=h4a9f257_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gds-tools=1.11.1.6=0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.3.0=h6a678d5_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - icu=73.1=h6a678d5_0
  - ipykernel=6.29.5=py313h06a4308_1
  - ipython=9.1.0=py313h06a4308_0
  - ipython_pygments_lexers=1.1.1=py313h06a4308_0
  - jedi=0.19.2=py313h06a4308_0
  - jupyter_client=8.6.3=py313h06a4308_0
  - jupyter_core=5.7.2=py313h06a4308_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcublas=12.6.4.1=0
  - libcublas-dev=12.6.4.1=0
  - libcufft=11.3.0.4=0
  - libcufft-dev=11.3.0.4=0
  - libcufile=1.11.1.6=0
  - libcufile-dev=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcurand-dev=10.3.7.77=0
  - libcusolver=11.7.1.2=0
  - libcusolver-dev=11.7.1.2=0
  - libcusparse=12.5.4.2=0
  - libcusparse-dev=12.5.4.2=0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libmpdec=4.0.0=h5eee18b_0
  - libnpp=12.2.5.30=0
  - libnpp-dev=12.2.5.30=0
  - libnvfatbin=12.6.77=0
  - libnvfatbin-dev=12.6.77=0
  - libnvjitlink=12.6.85=0
  - libnvjitlink-dev=12.6.85=0
  - libnvjpeg=12.3.1.117=0
  - libnvjpeg-dev=12.3.1.117=0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - matplotlib-inline=0.1.6=py313h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py313h06a4308_0
  - nsight-compute=2024.3.2.3=0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - parso=0.8.4=py313h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - platformdirs=4.3.7=py313h06a4308_0
  - prompt-toolkit=3.0.43=py313h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py313h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.19.1=py313h06a4308_0
  - python=3.13.2=hf623796_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python_abi=3.13=0_cp313
  - pyzmq=26.2.0=py313h6a678d5_0
  - readline=8.2=h5eee18b_0
  - six=1.17.0=py313h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.2=py313h5eee18b_0
  - traitlets=5.14.3=py313h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.45.1=py313h06a4308_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.7.0
      - acres==0.5.0
      - adjusttext==1.3.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - alembic==1.16.1
      - annotated-types==0.7.0
      - anyio==4.10.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - biopython==1.85
      - bleach==6.2.0
      - build==1.2.2.post1
      - certifi==2025.4.26
      - cffi==1.17.1
      - cfgv==3.4.0
      - chanfig==0.0.112
      - charset-normalizer==3.4.2
      - ci-info==0.3.0
      - click==8.2.0
      - cloudpickle==3.1.1
      - cmake==4.0.2
      - colorlog==6.9.0
      - configobj==5.0.9
      - configparser==7.2.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - danling==0.3.13
      - datasets==3.6.0
      - defusedxml==0.7.1
      - dill==0.3.8
      - distlib==0.3.9
      - docker-pycreds==0.4.0
      - easyevo2==0.1.21
      - einops==0.8.1
      - etelemetry==0.3.1
      - evo2==0.1.0
      - fair-esm==2.0.0
      - fastjsonschema==2.21.2
      - filelock==3.18.0
      - fitz==0.0.1.dev2
      - flash-attn==2.8.0.post2
      - fonttools==4.58.1
      - fqdn==1.5.1
      - frozenlist==1.6.0
      - fsspec==2025.3.0
      - gdown==5.2.0
      - gemmi==0.7.3
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gprof2dot==2025.4.14
      - graphviz==0.21
      - greenlet==3.2.2
      - griddataformats==1.0.2
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.9
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - identify==2.6.12
      - idna==3.10
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jinja2==3.1.6
      - joblib==1.5.1
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.7
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lazy-imports==1.0.0
      - lightning-utilities==0.14.3
      - llvmlite==0.44.0
      - looseversion==1.3.0
      - lxml==5.4.0
      - mako==1.3.10
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - matplotlib-venn==1.1.2
      - mda-xdrlib==0.2.0
      - mdanalysis==2.10.0
      - mdurl==0.1.2
      - mistune==3.1.4
      - ml-collections==1.1.0
      - mmtf-python==1.1.3
      - mpmath==1.3.0
      - mrcfile==1.5.4
      - msgpack==1.1.2
      - multidict==6.4.3
      - multimolecule==0.0.7
      - multiprocess==0.70.16
      - narwhals==2.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.5
      - nibabel==5.3.2
      - ninja==1.11.1.4
      - nipype==1.10.0
      - nodeenv==1.9.1
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - numba==0.61.2
      - numpy==2.2.5
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - optuna==4.3.0
      - packaging==25.0
      - pandas==2.2.3
      - pandas-stubs==2.3.2.250827
      - pandocfilters==1.5.1
      - pathlib==1.0.1
      - peft==0.15.2
      - pillow==11.2.1
      - pip==25.2
      - plotly==6.3.0
      - pre-commit==4.0.1
      - prometheus-client==0.22.1
      - propcache==0.3.1
      - protobuf==6.31.0
      - prov==2.0.2
      - ptflops==0.7.4
      - puremagic==1.29
      - py-spy==0.4.1
      - pyarrow==20.0.0
      - pybind11==2.13.6
      - pycparser==2.22
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pydot==4.0.1
      - pyfastx==2.2.0
      - pyhocon==0.3.61
      - pyparsing==3.2.3
      - pyproject-hooks==1.2.0
      - pysocks==1.7.1
      - python-json-logger==3.3.0
      - pytz==2025.2
      - pyxnat==1.6.3
      - pyyaml==6.0.2
      - rdflib==7.1.4
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==13.9.2
      - rinalmo==1.0.0
      - rna-fm==0.2.2
      - rpds-py==0.27.1
      - ruff==0.1.1
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.28.0
      - setproctitle==1.3.6
      - setuptools==80.9.0
      - shap==0.47.2
      - shellingham==1.5.4
      - simplejson==3.20.1
      - slicer==0.0.8
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - sqlalchemy==2.0.41
      - sympy==1.14.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.21.4
      - torch==2.7.1
      - torcheval==0.0.7
      - torchmetrics==1.7.4
      - tqdm==4.67.1
      - traits==7.0.2
      - transformer-engine==0.0.0
      - transformers==4.50.0
      - triton==3.3.1
      - typer==0.19.2
      - types-python-dateutil==2.9.0.20250822
      - types-pytz==2025.2.0.20250809
      - typing-extensions==4.14.1
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - umap==0.1.1
      - uri-template==1.3.0
      - urllib3==2.4.0
      - viennarna==2.7.0
      - virtualenv==20.31.2
      - vortex==0.0.2
      - wandb==0.19.11
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.14
      - xxhash==3.5.0
      - yarl==1.20.0
prefix: /home/sobhan/environments/flash
